src/examples/example.yml

`deploy_to_env` doesn't exist, the job name is `deploy_env`
`app_name` is not a valid parameter, use `chart_name`

Update example to match available options

---

.circleci/config.yml
README.md
src/@orb.yml
src/examples/slack_notification.yml
src/jobs/deploy_env.yml

With the current configuration, we only get Slack notifications about
successful deployments, despite having the notification steps in the
compiled CircleCI steps.
This is an attempt to enable notifications for all cases.
As part of this upgrade, Slack configuration needs to change.
- **old** `SLACK_WEBHOOK_URL`
- **new** `SLACK_ACCESS_TOKEN` through `moj-slack-notifications` context
Slack orb 4+ requires an application to be set up and a
`SLACK_ACCESS_TOKEN` variable. To enable this, we've installed an app
called `ci-deploy-to-cloud-platform` on the MoJ Slack instance.
The token is shared in the `moj-slack-notifications` CircleCI context.
Please see [the example notification workflow][ex] for a usage example.
[ex]: src/examples/slack_notification.yml

[semver:major] Upgrade Slack to notify on failed deploys

---

src/executors/node.yml
src/jobs/npm_security_audit.yml

* Updates the default node image to use the cimg/ circle images in place of circleci/ images.
* Avoids a re-install of npm:latest in the npm_security_audit job as npm and yarn are pre-installed in the cimg/ images
This is to resolve the failing npm_security_job across the node applications due to it installing npm v7.5.2 (latest) regardless of the node image being used, which subsequently fails attempting to install the audit-ci package.

[semver:minor] Update to cimg circle images and avoid re-installing latest npm in the npm_security_audit job

---

src/jobs/build_docker.yml

We ran into some cases where the image build used yesterday's base image
and it tripped our vulnerability scanning.
Since we knew it was fixed already, it was a stale image. To avoid, we
can now pull the base image every time: if it's up-to-date, great,
otherwise it must contain something meaningful.
Overall, it makes the build more predictable.

[semver:patch] Always pull base image on builds

---

src/commands/recall_container_image.yml
src/jobs/build_docker.yml
src/jobs/publish_docker.yml

This allows the built container image to be saved to the workspace and
recalled in subsequent jobs, meaning that you can build your container,
use it in several other jobs (i.e. CVE scanning, tests etc) without
having to publish it to the container repository first.
As a result, I've also introduced a separate `publish_docker` job here
too.

Allow the built docker container to be used in subsequent jobs.

---

src/commands/install_trivy.yml
src/jobs/trivy_latest_scan.yml
src/jobs/trivy_pipeline_scan.yml

This adds two trivy scans, one intended to scan the built container as
part of a pipeline run, and the other as a scheduled job to scan the
`latest` tag of a project to check for CVEs that have been identified
since the last deployment/build.

[semver:minor] Add jobs to scan the container images with Trivy

---

.circleci/config.yml
.gitignore
README.md
src/@orb.yml
src/examples/deployment_with_slack_and_changelog.yml
src/jobs/deploy_env.yml
src/scripts/version_history.sh

Extend the `deploy_env` job with an opt-in flag `show_changelog`, which, when `true`, annotates the deployment notification:
It will build the log based on the difference of
- the last deployed version sha from the `Deployment` in the cloud platform (or technically, any Kubernetes) namespace
- and the sha in the `APP_VERSION`
- it will display both squashed and merged PR commits
More details in cd413d6a7b8bdcc50255bda2060d1b56063c4b7d

[semver:minor] Deploy changelog

---

.circleci/config.yml
src/commands/install_git_lfs.yml
src/jobs/build_docker.yml

we are using Git LFS in https://github.com/ministryofjustice/hmpps-interventions-ui/ . we need it installed on the image that builds our docker images. this PR adds a command to the orb to install the inderlying library and the git hooks required to properly build our images.
for more information on git lfs see https://github.com/git-lfs/git-lfs

add command to install Git LFS

---

src/jobs/trigger_job.yml

We're using this approach to run end-to-end tests on our tooling after
one of the components have been pushed to an environment.
Here's an example of a test run using this code:
https://app.circleci.com/pipelines/github/ministryofjustice/manage-recalls-api/226/workflows/875d3b6f-98cf-41c2-9d03-20a706524d97/jobs/1115

[semver:minor] PUD-188: Add a job for triggering another CircleCI pipeline

---

src/scripts/version_history.sh

Shorten merge-style changelogs by
- Shortening dependabot branch names into a dependabot emoji
- "Merge pull request" → "PR"
- "from ministryofjustice/" → ""
Examples:
**Before**
```
c64e729d Merge pull request #723 from ministryofjustice/dependabot/npm_and_yarn/aws-sdk-2.973.0
24f96ba5 Merge pull request #697 from ministryofjustice/IC-1919-initial-assessment-check-answers
```
**After**
```
c64e729d PR #723 :dependabot:npm_and_yarn/aws-sdk-2.973.0
24f96ba5 PR #697 IC-1919-initial-assessment-check-answers
```

[semver:minor] Shorten merge-style changelogs

---

src/examples/example.yml

To make it easier to look up a default configuration
Without the `context` part, the job fails when trying to send the Slack message

[semver:skip] Expand example around npm_security_audit

---

src/jobs/sentry_release_and_deploy.yml

This separates out the deployment and release creation steps so we can
create the release in DEV on the first deployment and only record
deployments in subsequent environments.

[semver:patch] Bugfix: We should only "create" a release once in Sentry

---

src/jobs/sentry_release_and_deploy.yml

`SENTRY_ORG` and `SENTRY_PROJECT` were not being persisted between steps
in the build causing errors on all runs.

[semver:patch] Bugfix persist env vars between steps

---

src/jobs/build_docker.yml

We'd like to pass additional `--build-arg` options to our builds...

[semver:patch] Allow additional cli args to be passed to docker build

---

src/scripts/version_history.sh

_This is applicable for deploy_env jobs with `show_changelog: true` and `slack_notification: true`_
For example,
```
bbc12fe5 PR #713 cluster-migration/delete-research-environment
083a79a5 PR #712 cluster-migration/add-parallel-dev-deployment
4a8704de PR #703 data/enforce-descriptions
f3882aa6 PR #709 monitoring/make-casenote-errors-contain-ids
d3ad9f21 PR #694 reports/prepare-to-remove-v1-ndmis-report
99903087 PR #699 xHVqOzpw/155-notify-appointment-outcome-feature-flag
```
becomes
```
bbc12fe5 PR #713 cluster-migration/delete-research-environment (2 hours ago)
083a79a5 PR #712 cluster-migration/add-parallel-dev-deployment (18 hours ago)
4a8704de PR #703 data/enforce-descriptions (24 hours ago)
f3882aa6 PR #709 monitoring/make-casenote-errors-contain-ids (24 hours ago)
d3ad9f21 PR #694 …
```

[semver:patch] Show relative merge times in changelog

---

src/jobs/veracode_policy_scan.yml

Bump veracode wrapper from 21.6.8.0 to 21.12.9.1
Randomly noticed it's out of date. Is this bump safe?

[semver:patch] Bump veracode wrapper from 21.6.8.0 to 21.12.9.1

---

src/commands/install_git_crypt.yml
src/jobs/deploy_env.yml
src/jobs/helm_lint.yml
src/scripts/deploy_env.sh
src/scripts/helm_lint.sh

This will enable clients to have secrets stored (encrypted) within their repositories and used a deploy time.  The secrets should be stored in files called `secrets-<env>.yaml` alongside the `values-<env>.yaml` files.

Update the deploy job to be able to use `git-crypt`

---

src/jobs/trigger_job.yml

This parameter wasn't being used meaning that all triggers were hard
coded to a 500 second timeout.

[semver:patch] Bugfix: Use the `follow_timeout` parameter.

---

src/jobs/build_docker.yml

This should help teams deal with the gradle slowness we're seeing at the moment.
ref: https://mojdt.slack.com/archives/C69NWE339/p1646727334689739

[semver:patch] Allow the setting of no_output_timeout on the docker_build step

---

src/scripts/deploy_env.sh

We're migrating one of our services to live and the initial helm upgrade is timing out, this will hopefully fix it.

[semver:patch] Increase the helm timeout to 15m by default

---

src/jobs/build_multiplatform_docker.yml

Copy of the docker build to try out the multi platform.  Not sure if we want to introduce for all builds, will trial first.
```
 diff build_docker.yml build_multiplatform_docker.yml
19c19
<     default: "20.10.6"
---
>     default: "20.10.11"
75a76,82
>       name: Setup buildx
>       command: |
>         docker context create multi-arch-build
>         docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
>         docker run --rm --privileged tonistiigi/binfmt --install all
>         docker buildx create --use multi-arch-build --platform linux/arm64,linux/amd64
>   - run:
79c86,88
<         docker build --pull \
---
>         docker buildx build \
>           --platform linux/amd64,linux/arm64 --pull \
>           --progress plain \
```

[semver:patch] SDI-189: ✨ Try out buildx for multi arch builds

---

README.md
src/jobs/npm_security_audit.yml

This will allow us to fix this failing build:
https://app.circleci.com/pipelines/github/ministryofjustice/wmt-web/1644/workflows/c5883171-0154-4ff0-bc3d-d9a80ec73554/jobs/9288

[semver:minor] Allow the version of the node executor for npm_security_audit to be set

---

src/commands/veracode_prepare_artifacts.yml
src/jobs/build_docker.yml
src/jobs/build_multiplatform_docker.yml
src/jobs/publish_docker.yml
src/jobs/trivy_latest_scan.yml
src/jobs/trivy_pipeline_scan.yml

Circle have recommended we use the default (i.e. latest) version of docker when using the setup_remote_docker step. Details in this post: https://discuss.circleci.com/t/setup-remote-docker-architecture-change/45303.
As we are removing a parameter this change is breaking, hence a major version upgrade.

[semver:release] SDI-411 Use default docker version

---

src/jobs/deploy_env.yml

Fixing issue where backticks in commit messages break deployments

[semver:minor] Replace backtick with single quote

---

src/jobs/gradle_owasp_dependency_check.yml

https://dsdmoj.atlassian.net/browse/INC-1226
Since upgrading [hmpps-incentives-api](https://github.com/ministryofjustice/hmpps-incentives-api) to Gradle 8 we were seeing the `hmpps/gradle_owasp_dependency_check` job fail with the following error (see [example](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-incentives-api/1860/workflows/8808b70a-e9bd-49ed-b558-e25988eeb5cc/jobs/6855/parallel-runs/0/steps/0-108)):
```
* What went wrong:
Execution failed for task ':dependencyCheckAnalyze'.
> Could not resolve all dependencies for configuration ':agentDeps'.
> Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
> No matching toolchains found for requested specification: {languageVersion=19, vendor=any, implementation=vendor-specific}.
> No locally …
```

[semver:minor] INC-1226: add param for JDK executor version for owasp job

---

src/@orb.yml
src/jobs/deploy_env.yml

This change ensures we always get release notifications for production environments sent to the slack channel `dps-releases`.  If a team has set a channel other than this, then that channel will be notified also.

[semver:patch]: 🔧 Always send slack release notifications to central channel, optionally also send to team channel

---

src/jobs/deploy_env.yml

We currently get the message
> This job is using a deprecated deploy step, please [update .circleci/config.yml](https://circleci.com/docs/migrate-from-deploy-to-run/) to use a run step
in our pipelines, simple change

[semver:minor] SDIT-1430: 🔧 Switch deploy to run

---

src/executors/java_localstack_postgres.yml

Add postgres_db parameter to java_localstack_postgres executor, so it can create postgres container same as java_postgres and node_redis_postgres.

[semver:minor]: Add postgres_db parameter to java_localstack_postgres executor

---

release-notes/9.x.md
src/jobs/build_multiplatform_docker.yml

Some circle-ci builds are getting errors relating to docker layer caching. After raising a ticket request with the circle ci team they suggested adding a --name attribute to the docker buildx create command, to fix this.
## Additional Info
Ticket: https://support.circleci.com/hc/en-us/requests/152193?page=1
Response
--
Hi Aaron,
As an additional follow up to Henna's previous message, I'd like to bring up a few points regarding your use of buildx
When using buildx, we recommend in our documentation that builders are --named in order to successfully work with DLC.
Documentation: https://circleci.com/docs/docker-layer-caching/#buildx-builder-instances

[semver:minor] Add --name attribute to docker buildx create command to fix docker layer caching errors

---

release-notes/9.x.md
src/jobs/build_multiplatform_docker.yml

Without this attribute the docker layer cache which is enabled, will not function correctly. As it requires a name for the build context to find cached layers, without it, a random name is generated every time and nothing is ever cached.
Also update release notes to document changes.

 [semver:minor] Add "--name" attribute to build_multiplatform_docker job buildx step

---

src/jobs/trivy_latest_scan.yml

Attempting to trigger publishing of the Orb this time.

[semver:minor] Update to use backup Trivy repositories

---

src/scripts/deploy_env.sh

Adding extra helm value to help track enviroments - this value is going to be picked up by generic-prometheus-alerts chart and enable better filtering of alerts based on environment.  See https://github.com/ministryofjustice/hmpps-helm-charts/pull/175

[semver:minor] Add value for environment to helm args - used by prometheus alert rules for better filtering
