src/jobs/veracode_pipeline_scan.yml, src/jobs/veracode_policy_scan.yml
=> [semver:minor] Add veracode_policy_scan job

src/executors/node.yml
=> [semver:patch] Bump default node exectutor version

src/jobs/veracode_pipeline_scan.yml, src/jobs/veracode_policy_scan.yml
=> [semver:patch] Add param to control dir where source files are located in the docker image

src/jobs/helm_lint.yml
=> [semver:patch] - add helm dependency update to helm lint job

src/jobs/veracode_policy_scan.yml
=> [semver:patch] - add 'teams' parameter to veracode policy scan.

src/jobs/trivy_latest_scan.yml
=> [semver:patch] Ensure trivy scan job uses latest image from repo

.circleci/config.yml, src/jobs/deploy_env.yml, src/scripts/version_history.sh
=> [semver:patch] Fix changelog - Fail gracefully when no previous deployment found

src/jobs/build_docker.yml, src/jobs/publish_docker.yml, src/jobs/trivy_latest_scan.yml, src/jobs/trivy_pipeline_scan.yml
=> [semver:minor] Add param for docker engine version with v20.10.6 by default

src/commands/veracode_prepare_artifacts.yml, src/executors/default.yml, src/executors/java.yml, src/executors/java_mssql.yml, src/executors/node.yml, src/executors/node_redis.yml
=> [semver:patch] Add missing docker version param. Add resource class param for executors.

src/commands/veracode_prepare_artifacts.yml, src/jobs/veracode_pipeline_scan.yml
=> [semver:patch] Update veracode pipeline scan job to use baseline file, and send results via slack

src/commands/slack_message_results.yml
=> [semver:patch] Allow processing of slack message results to fail gracefully

src/@orb.yml, src/jobs/build_docker.yml, src/jobs/deploy_env.yml
Requires Jira integration to be enabled in your CircleCI project settings, as well as the `hmpps-common-vars` context. See https://dsdmoj.atlassian.net/wiki/spaces/PINT/pages/3887562955/Integrate+Jira+with+CircleCI
=> [semver:minor] added Jira integration

src/jobs/veracode_pipeline_scan.yml
Reverts ministryofjustice/hmpps-circleci-orb#111
=> [semver:patch] Revert "[semver:patch] SDI-171: 🐛 Cope with veracode scan now writing policy with spaces in it"

src/jobs/build_multiplatform_docker.yml
load is default for standard docker, but not run for multi platform builds and not even supported - see https://github.com/docker/buildx/issues/59
=> [semver:patch] SDI-189: ✨ Fix multi platform not publishing

src/jobs/build_docker.yml
Adding an optional parameter to publish docker image with an additional image tag
=> Added optional additional  docker tag

src/jobs/build_docker.yml
Adding [semver:minor] to summary to support deploy
=> [semver:minor] added additional_docker_tag description

src/scripts/deploy_env.sh
---
title: ''
labels: ''
assignees: ''
---
=> [semver:patch] add debug output for deploy job environment variables

src/scripts/deploy_env.sh
---
title: ''
labels: ''
assignees: ''
---
=> [semver:patch] attempt to resolve circleci bug and add further debugging output to deploy job.

src/scripts/deploy_env.sh
---
title: ''
labels: ''
assignees: ''
---
=> [semver:patch] add better debugging out for deploy_env job

release-notes/7.0.md, src/commands/veracode_prepare_artifacts.yml, src/jobs/build_docker.yml, src/jobs/build_multiplatform_docker.yml
Minor version since it's adding new functionality?
=> [semver:patch] HEAT-106: Pass CircleCI branch name into docker build

.circleci/config.yml
---
title: ''
labels: ''
assignees: ''
---
=> [semver:patch] Fix Orb authorization errors

src/executors/java_localstack_postgres.yml
Reverts ministryofjustice/hmpps-circleci-orb#155
=> [semver:patch] Revert "Add postgres db param to java localstack executor"

src/scripts/deploy_env.sh
---
title: ''
labels: ''
assignees: ''
---
=> [semver:minor] Add IP groups allowlist to helm deploy args

src/executors/java.yml
---
title: ''
labels: ''
assignees: ''
---
=> [semver:patch]: 🔧 Increase default JVM heap size

src/executors/java_localstack_postgres.yml
Reverts ministryofjustice/hmpps-circleci-orb#172
=> [semver:minor] Revert "[semver:minor]: Add postgres_db parameter to java_localstack_postgres executor"

README.md, release-notes/9.x.md, src/executors/java_localstack_postgres.yml, src/executors/java_localstack_postgres_with_db_name.yml, src/executors/localstack.yml
[Demo of the environment variables using an inline orb](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-person-record/1845/workflows/16483fb7-fd4f-42f7-9f0f-9be827c7dfc1/jobs/5366)
=> [semver:major] CPR-330 get rid of localstack warnings when running v3

src/executors/java_localstack_postgres.yml, src/executors/java_localstack_postgres_with_db_name.yml, src/executors/java_postgres.yml, src/executors/node_redis_postgres.yml, src/jobs/database_schema_report.yml
Also specifying port number on executors
=> [semver:minor] CVSL-2418: Allow overriding extra properties for schemaspy job

src/commands/slack_message_results.yml, src/scripts/sanitise_slack_alert.sh
Adds a regex to handle single quotes in trivy failure messages.
=> [semver:patch] Slack single quote sanitisation
